server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka

#openfegin中默认未响应报错时间为1秒(将最大时间调到5秒)
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug



